apiVersion: v1
kind: Pod
metadata:
  name: proxy-pod
spec:
  containers:
    - name: redsocks
      image: vandreykiv/redsocks:latest
      command:
        - /usr/local/bin/redsocks.sh
      args:
        - proxy-server
        - "3128"
      securityContext:
        capabilities:
          add:
            - NET_ADMIN
        privileged: true
    - name: busybox
      image: yauritux/busybox-curl
      command:
        - sleep
      args:
        - 300m
